[workspace]
resolver = "2"

members = [
    "vhost-device-gpio",
    "vhost-device-i2c",
    "vhost-device-rng",
    "vhost-device-scsi",
    "vhost-device-scmi",
    "vhost-device-vsock",
    "staging/vhost-device-sound",
    "staging/vhost-device-video",
]
